# Generated by Django 4.2.29 on 2026-04-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TufProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_status",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("INTERN", "Intern"),
                            ("PRO", "Professional"),
                        ],
                        default="USER",
                        max_length=10,
                        verbose_name="Account Status",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Verification Status"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        help_text="Height in centimeters",
                        null=True,
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        help_text="Weight in kilograms",
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Biography"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuf_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Associated User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "tuf_profiles",
            },
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(max_length=255, verbose_name="Food Name"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="meal_images/%Y/%m/%d/", verbose_name="Food Image"
                    ),
                ),
                (
                    "calories",
                    models.FloatField(default=0.0, verbose_name="Calories (kcal)"),
                ),
                ("protein", models.FloatField(default=0.0, verbose_name="Protein (g)")),
                (
                    "carbs",
                    models.FloatField(default=0.0, verbose_name="Carbohydrates (g)"),
                ),
                ("fat", models.FloatField(default=0.0, verbose_name="Fat (g)")),
                (
                    "ai_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="AI model confidence score (0.0 to 1.0)",
                        verbose_name="AI Confidence",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Entry",
                "verbose_name_plural": "Meal Entries",
                "db_table": "meal_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
