# Generated by Django 4.2.29 on 2026-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tufdiet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodNutritionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("calories", models.FloatField(default=0)),
                ("protein", models.FloatField(default=0)),
                ("carbs", models.FloatField(default=0)),
                ("fat", models.FloatField(default=0)),
                ("usage_count", models.PositiveIntegerField(default=1)),
                ("last_used", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Food Nutrition Cache",
                "db_table": "food_nutrition_cache",
                "ordering": ["-usage_count"],
            },
        ),
        migrations.AlterField(
            model_name="mealentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="meal_images/%Y/%m/%d/",
                verbose_name="Food Image",
            ),
        ),
    ]
