# Generated by Django 4.2.30 on 2026-04-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tufdiet', '0002_foodnutritioncache_alter_mealentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tufprofile',
            name='activity_level',
            field=models.CharField(choices=[('SEDENTARY', 'Sedentary (little or no exercise)'), ('LIGHT', 'Light (exercise 1-3 days/week)'), ('MODERATE', 'Moderate (exercise 3-5 days/week)'), ('ACTIVE', 'Active (exercise 6-7 days/week)'), ('VERY_ACTIVE', 'Very Active (hard exercise daily)')], default='MODERATE', max_length=20, verbose_name='Activity Level'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='bmr',
            field=models.FloatField(blank=True, null=True, verbose_name='Basal Metabolic Rate (BMR)'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='goal',
            field=models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('GAIN_WEIGHT', 'Gain Weight'), ('MAINTAIN', 'Maintain Weight'), ('MUSCLE_GAIN', 'Build Muscle (High Protein)'), ('FAT_BURN', 'Fat Burn (High Protein)')], default='MAINTAIN', max_length=20, verbose_name='Fitness Goal'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='target_calories',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Daily Calories'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='target_carbs',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Carbohydrates (g)'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='target_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Fat (g)'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='target_protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Protein (g)'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='tdee',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Daily Energy Expenditure'),
        ),
    ]
