# Generated by Django 4.2.30 on 2026-04-26 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tufdiet', '0003_tufprofile_activity_level_tufprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tufprofile',
            name='last_water_reset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Water Reset Date'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='social_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Social Media Link'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='water_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='Water Consumed Today'),
        ),
        migrations.AddField(
            model_name='tufprofile',
            name='water_target',
            field=models.PositiveIntegerField(default=8, help_text='Daily water glasses target', verbose_name='Water Target (glasses)'),
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'weight_history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
