# Generated by Django 4.2.30 on 2026-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tufdiet', '0004_extend_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tufprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='tufprofile',
            name='goal',
            field=models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('GAIN_WEIGHT', 'Gain Weight'), ('MAINTAIN_FAT_LOSS', 'Maintain / Fat Loss')], default='MAINTAIN_FAT_LOSS', max_length=20, verbose_name='Fitness Goal'),
        ),
    ]
