# Generated by Django 4.2.30 on 2026-06-14 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tufdiet', '0005_update_goals_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=20)),
                ('food_name', models.CharField(max_length=255)),
                ('target_calories', models.FloatField()),
                ('target_protein', models.FloatField()),
                ('target_carbs', models.FloatField()),
                ('target_fat', models.FloatField()),
                ('is_eaten', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_plan', to='tufdiet.mealentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_plan_meals',
                'ordering': ['date', 'meal_type'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
    ]
