# Generated by Django 4.2.30 on 2026-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tufdiet', '0006_dietplanmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplanmeal',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='Recipe'),
        ),
    ]
