# Generated by Django 4.2.30 on 2026-06-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tufdiet', '0007_dietplanmeal_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dietplanmeal',
            unique_together=set(),
        ),
    ]
