# Generated by Django 4.2.30 on 2026-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tufdiet', '0008_alter_dietplanmeal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplanmeal',
            name='suggested_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Suggested Eating Time'),
        ),
    ]
